import Head from "next/head";
import Navbar from "../components/Navbar";
import ContactForm from "../components/ContactForm";
import Footer from "../components/Footer";
import EventTwo from "../components/EventTwo";
import CaseStudyTwo from "../components/CaseStudyTwo";
import AlternLanding from "../components/AlternLanding";
import SupportBusinessRecord from "../components/SupportBusinessRecord";
import SectionFreeRes from "../components/SectionFreeRes";


export default function Home({ homepage }) {
  return (
    <div>
      <Head>
        <title>Croner datoCMS test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
        <AlternLanding />
        <SupportBusinessRecord />
        <EventTwo />
        <SectionFreeRes />
        <CaseStudyTwo />
        <ContactForm />
        <Footer />
      </div>
    </div>
  );
}

